// GERADO por backend/scripts/gerar-endpoints.mjs — NÃO EDITE À MÃO.
// A lista anterior era mantida manualmente e passou a documentar rotas
// inexistentes. Para mudar uma descrição, edite DESCRICOES no gerador e rode
// `npm run endpoints` no backend.
export const ENDPOINTS_API = [
  {"metodo":"GET","rota":"/api/anamnese/paciente/:pacienteId","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/anamnese/paciente/:pacienteId","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/auth/aceitar-termos","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/auth/consultorio","auth":true,"desc":""},
  {"metodo":"DELETE","rota":"/api/auth/conta","auth":true,"desc":"Exclui a conta (LGPD)"},
  {"metodo":"POST","rota":"/api/auth/esqueci-senha","auth":false,"desc":"Envia e-mail de redefinição de senha"},
  {"metodo":"GET","rota":"/api/auth/exportar","auth":true,"desc":"Exporta os dados da conta (LGPD)"},
  {"metodo":"POST","rota":"/api/auth/login","auth":false,"desc":"Login da nutricionista (retorna access + refresh)"},
  {"metodo":"POST","rota":"/api/auth/logout","auth":false,"desc":"Revoga o refresh token"},
  {"metodo":"GET","rota":"/api/auth/me","auth":true,"desc":"Dados da nutricionista logada"},
  {"metodo":"POST","rota":"/api/auth/paciente/esqueci-senha","auth":false,"desc":""},
  {"metodo":"POST","rota":"/api/auth/paciente/login","auth":false,"desc":""},
  {"metodo":"POST","rota":"/api/auth/paciente/logout","auth":false,"desc":""},
  {"metodo":"POST","rota":"/api/auth/paciente/redefinir-senha","auth":false,"desc":""},
  {"metodo":"POST","rota":"/api/auth/paciente/reenviar-verificacao","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/auth/paciente/refresh","auth":false,"desc":""},
  {"metodo":"POST","rota":"/api/auth/paciente/register","auth":false,"desc":""},
  {"metodo":"POST","rota":"/api/auth/paciente/verificar-email","auth":false,"desc":""},
  {"metodo":"PUT","rota":"/api/auth/perfil","auth":true,"desc":"Atualiza o perfil da nutricionista"},
  {"metodo":"PUT","rota":"/api/auth/perfil/foto","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/auth/redefinir-senha","auth":false,"desc":"Redefine a senha usando o token do e-mail"},
  {"metodo":"POST","rota":"/api/auth/reenviar-verificacao","auth":true,"desc":"Reenvia o e-mail de verificação"},
  {"metodo":"POST","rota":"/api/auth/refresh","auth":false,"desc":"Troca refresh por novo par de tokens"},
  {"metodo":"POST","rota":"/api/auth/register","auth":false,"desc":"Cadastro de nutricionista"},
  {"metodo":"POST","rota":"/api/auth/verificar-email","auth":false,"desc":"Confirma o e-mail pelo token"},
  {"metodo":"POST","rota":"/api/billing/asaas-webhook","auth":false,"desc":""},
  {"metodo":"POST","rota":"/api/billing/cancelar-pix","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/billing/checkout","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/billing/checkout-pix","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/billing/pix-status","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/billing/portal","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/billing/status","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/billing/upgrade","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/billing/webhook","auth":false,"desc":""},
  {"metodo":"POST","rota":"/api/checklist","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/checklist/historico","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/checklist/hoje","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/ciclos","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/ciclos","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/ciclos/:id","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/ciclos/:id/encerrar","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/ciclos/:id/mensagem-nutri","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/ciclos/:id/ranking","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/ciclos/:id/relatorio/:pacienteId","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/ciclos/atual","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/ciclos/paciente/:cicloId/relatorio","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/ciclos/paciente/atual","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/consultas","auth":true,"desc":"Lista consultas (inicio, fim)"},
  {"metodo":"POST","rota":"/api/consultas","auth":true,"desc":"Cria consulta"},
  {"metodo":"PATCH","rota":"/api/consultas/:id","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/dashboard","auth":true,"desc":"Métricas resumo do dashboard"},
  {"metodo":"GET","rota":"/api/dashboard/alertas","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/dashboard/ligas","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/desafios","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/desafios","auth":true,"desc":""},
  {"metodo":"DELETE","rota":"/api/desafios/:id","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/desafios/:id","auth":true,"desc":""},
  {"metodo":"PATCH","rota":"/api/desafios/:id","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/desafios/:id/lembrete","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/desafios/:id/participantes","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/desafios/:id/progresso","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/desafios/resumo","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/diario/:id","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/diario/:id/mensagem","auth":true,"desc":""},
  {"metodo":"PATCH","rota":"/api/diario/:id/registro/:registroId/ajuste-lido","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/feed","auth":true,"desc":"Feed de posts dos pacientes"},
  {"metodo":"POST","rota":"/api/feed","auth":true,"desc":""},
  {"metodo":"DELETE","rota":"/api/feed/:id","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/feed/:id/comentarios","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/feed/:id/comentarios","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/feed/:id/curtir","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/feed/engajadores","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/feed/mural","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/financeiro/asaas-key","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/financeiro/asaas-status","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/financeiro/asaas-webhook","auth":false,"desc":""},
  {"metodo":"DELETE","rota":"/api/financeiro/cobrar/:cobrancaId/pix","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/financeiro/cobrar/:cobrancaId/pix","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/financeiro/dashboard","auth":true,"desc":"Resumo financeiro da clínica"},
  {"metodo":"GET","rota":"/api/financeiro/plano/:pacienteId","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/financeiro/plano/:pacienteId","auth":true,"desc":""},
  {"metodo":"DELETE","rota":"/api/fotos/:fotoId","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/fotos/:fotoId/imagem","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/fotos/:pacienteId","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/fotos/:pacienteId/meta","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/health","auth":false,"desc":""},
  {"metodo":"GET","rota":"/api/health/midia","auth":false,"desc":""},
  {"metodo":"GET","rota":"/api/horarios","auth":true,"desc":"Horários de atendimento"},
  {"metodo":"POST","rota":"/api/horarios","auth":true,"desc":""},
  {"metodo":"DELETE","rota":"/api/horarios/:id","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/lembretes","auth":true,"desc":""},
  {"metodo":"PATCH","rota":"/api/lembretes/:id","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/mensagens","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/mensagens/conversas","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/mensagens/nao-lidas","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/mensagens/paciente/:pacienteId","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/mensagens/thread/:pacienteId","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/mensagens/thread/:pacienteId","auth":true,"desc":""},
  {"metodo":"PATCH","rota":"/api/mensagens/thread/:pacienteId/lida","auth":true,"desc":""},
  {"metodo":"DELETE","rota":"/api/notificacoes/subscribe","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/notificacoes/subscribe","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/notificacoes/vapid-public-key","auth":false,"desc":""},
  {"metodo":"GET","rota":"/api/onboarding","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/onboarding/concluir","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/onboarding/convite-enviado","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/onboarding/iniciar","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/paciente-app/consultas","auth":true,"desc":""},
  {"metodo":"DELETE","rota":"/api/paciente-app/conta","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/paciente-app/exportar","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/paciente-app/feed","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/paciente-app/feed","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/paciente-app/feed/:id/comentarios","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/paciente-app/feed/:id/comentarios","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/paciente-app/feed/:id/curtir","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/paciente-app/foto-perfil","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/paciente-app/frase-motivacional","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/paciente-app/me","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/paciente-app/mensagens","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/paciente-app/mensagens","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/paciente-app/notificacao-aberta","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/paciente-app/pagamentos","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/paciente-app/perfil","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/paciente-app/ping","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/paciente-app/plano-alimentar","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/paciente-app/prefs-notificacao","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/paciente-app/prefs-notificacao","auth":true,"desc":""},
  {"metodo":"DELETE","rota":"/api/paciente-app/push/subscribe","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/paciente-app/push/subscribe","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/paciente-app/ranking","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/pacientes","auth":true,"desc":"Lista pacientes com paginação (busca, status, limit, page)"},
  {"metodo":"POST","rota":"/api/pacientes","auth":true,"desc":"Cria paciente (gera convite individual)"},
  {"metodo":"DELETE","rota":"/api/pacientes/:id","auth":true,"desc":"Anonimiza e desativa o paciente (LGPD)"},
  {"metodo":"GET","rota":"/api/pacientes/:id","auth":true,"desc":"Dados completos do paciente"},
  {"metodo":"PUT","rota":"/api/pacientes/:id","auth":true,"desc":"Atualiza paciente"},
  {"metodo":"POST","rota":"/api/pacientes/:id/consultas","auth":true,"desc":""},
  {"metodo":"PATCH","rota":"/api/pacientes/:id/consultas/:consultaId","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/pacientes/:id/contatos","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/pacientes/:id/convite","auth":true,"desc":"(Re)gera o convite individual do paciente"},
  {"metodo":"PATCH","rota":"/api/pacientes/:id/foto-inicial","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/pacientes/:id/plano-missoes","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/pacientes/:id/relatorio-mensal","auth":true,"desc":"Relatório mensal (base do PDF)"},
  {"metodo":"GET","rota":"/api/ranking","auth":true,"desc":"Ranking de pacientes"},
  {"metodo":"GET","rota":"/api/ranking/:nutricionistaId","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/ranking/atualizar","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/ranking/config","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/ranking/config","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/ranking/ligas","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/registro-fotos/:pacienteId","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/registro-fotos/:pacienteId","auth":true,"desc":""},
  {"metodo":"DELETE","rota":"/api/registro-fotos/:registroId","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/registros","auth":true,"desc":"Check-in do dia do paciente (one-shot, 409 se repetido)"},
  {"metodo":"GET","rota":"/api/registros-feed","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/registros-feed/:id/validar","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/registros-feed/paciente/:pacienteId/nudge","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/registros/:id/ajuste","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/registros/desafios","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/registros/desafios/:id/cumprir-hoje","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/registros/dia","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/registros/dia/fechar","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/registros/evolucao","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/registros/foto-evolucao","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/registros/historico","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/registros/hoje","auth":true,"desc":""},
  {"metodo":"PUT","rota":"/api/registros/humor","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/registros/medicao","auth":true,"desc":""},
  {"metodo":"POST","rota":"/api/registros/pedir-ajuste","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/registros/ranking","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/registros/resumo","auth":true,"desc":""},
  {"metodo":"GET","rota":"/api/relatorios","auth":true,"desc":"Insights agregados da carteira"},
] as const;
